// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Core.Models.DAL;
using Core.ViewModels.Beer;
using Foundation;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS;
using Int.iOS.Factories.Adapter;
using iOS.Helpers;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class Order : BasePageNavigation<OrderViewModel>
    {
        public Order(IntPtr handle) : base(handle) { }

        private Action<string> Result { get; set; }

        protected override void BindViews()
        {
            base.BindViews();

            var source = ComponentViewSourceFactory.CreateForTable(nameof(OrderCell),
                                                            new List<IOrderContent>(),
                                                            TableView,
                                                            crossCellModel: new OrderViewModel.OrderListCell(ModelView));

            TableView.Source = source;

            ModelView.GetPayment -= ModelView_GetPayment;
            ModelView.GetPayment += ModelView_GetPayment;
        }

        private void Payment()
        {
            AppTools.InvokeOnMainThread(() =>
            {
                PPHelper.Buy((state, res) =>
                {
                    switch (state)
                    {
                        case (PPHelper.State.Succefull):
                            OnSuccesPay(res);
                            break;
                        case (PPHelper.State.UserCancel):
                            //OnCancelPay();
                            break;
                        default:
                            OnFailedPay();
                            break;
                    }
                });
            });
        }

        private void ModelView_GetPayment(Action<string> arg)
        {
            Payment();
            Result = arg;
        }

        #region PayPalResponseHandlers

        private void OnSuccesPay(NSDictionary paymentData)
        {
            Result?.Invoke(PPHelper.GetPaymentIdFromConfirmationResponse(paymentData));
        }

        private void OnCancelPay() => ShowError("Payment cancelled");

        private void OnFailedPay() => ShowError("Payment failed");

        #endregion
    }

    partial class Order
    {
        [CrossView(nameof(OrderViewModel.OrderBarText))]
        UILabel view1 => lblBarTable;

        [CrossView(nameof(OrderViewModel.OrderTableText))]
        UILabel view2 => lblOrderTable;

        [CrossView(nameof(OrderViewModel.ListView))]
        UITableView propName2 => TableView;

        [CrossView(nameof(OrderViewModel.ContentView))]
        UIView propName3 => viewBackroundContent;
    }
}
