// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class EventDetails : BasePageNavigation<EventDetailsViewModel>
    {
        public EventDetails(IntPtr handle) : base(handle) { }
    }

    partial class EventDetails
    {
        [CrossView(nameof(EventDetailsViewModel.BackgroundContent))]
        UIView view15 => viewTinImageBackround;

        [CrossView(nameof(EventDetailsViewModel.EventImage))]
        UIImageView view2 => imgMain;

        [CrossView(nameof(EventDetailsViewModel.TimeEventBackground))]
        UIImageView view3 => imgDate;

        [CrossView(nameof(EventDetailsViewModel.TimeEvent))]
        UILabel view4 => lblDate;

        [CrossView(nameof(EventDetailsViewModel.HourEvent))]
        UILabel view8 => lblHour;

        [CrossView(nameof(EventDetailsViewModel.EventName))]
        UILabel view5 => lblTitle;

        [CrossView(nameof(EventDetailsViewModel.EventDescription))]
        UILabel view7 => lblDesc;


        [CrossView(nameof(EventDetailsViewModel.SeparatorImage))]
        UIImageView view23 => imgSeparator;
    }
}
