// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace iOS.Storyboard
{
    public partial class HeaderView : UIViewController
    {
        public HeaderView(IntPtr handle) : base(handle) { }

        public UILabel TextHeader => lblTitle;
        public UILabel TextHeaderCounter => lblCounterShop;

        public UIImageView ImageLeft => imgLeft;
        public UIImageView ImageRight => imgRight;

        public UIView ViewAreLeft => viewClickLeft;
        public UIView ViewAreRight => viewClickRight;

        public UIView ViewLine => viewLine;
    }
}
