// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels.Beer;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class Code : BasePageNavigation<CodeViewModel>
    {
        public Code(IntPtr handle) : base(handle) { }
    }

    public partial class Code
    {
        [CrossView(nameof(CodeViewModel.TitleText))]
        public UILabel view111 => lblTitleQr;

        [CrossView(nameof(CodeViewModel.TableNrText))]
        UILabel view21 => lblTableNr;

        [CrossView(nameof(CodeViewModel.TableNrValueText))]
        UILabel view31 => lblTableNrValue;

        [CrossView(nameof(CodeViewModel.ConfirmTableText))]
        UILabel view41 => lblConfirmTable;

        [CrossView(nameof(CodeViewModel.ViewQR))]
        UIView view51 => viewQR;


        [CrossView(nameof(CodeViewModel.View1))]
        UIView view6 => line1;

        [CrossView(nameof(CodeViewModel.View2))]
        UIView view7 => line2;

        [CrossView(nameof(CodeViewModel.View3))]
        UIView view8 => line3;

        [CrossView(nameof(CodeViewModel.View4))]
        UIView view9 => line4;

        [CrossView(nameof(CodeViewModel.View5))]
        UIView view10 => line5;

        [CrossView(nameof(CodeViewModel.View6))]
        UIView view11 => line6;

        [CrossView(nameof(CodeViewModel.View7))]
        UIView view12 => line7;

        [CrossView(nameof(CodeViewModel.View8))]
        UIView view13 => line8;


        [CrossView(nameof(CodeViewModel.ImageQR))]
        UIImageView view14 => imgQR;

        [CrossView(nameof(CodeViewModel.ImageScan))]
        UIImageView view15 => imgLoading;

        [CrossView(nameof(CodeViewModel.ContentView))]
        UIView propName3 => viewBackroundContent;
    }
}
