// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.Models.DAL;
using Core.ViewModels.Beer;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.CellView;
using UIKit;

namespace iOS.Storyboard
{
    public partial class OrderBarCell : ComponentTableViewCell<IOrderContent>
    {
        public OrderBarCell(IntPtr handle) : base(handle) { }

        protected override UIColor ColorSelector { get => UIColor.Clear; set => base.ColorSelector = value; }

        [CrossView(nameof(OrderBarViewModel.OrderListBaseCell.CellContentRootView))]
        public UIView view11 => mainRoot;

        [CrossView(nameof(OrderBarViewModel.OrderListBaseCell.CategoryImage))]
        public UIImageView view2 => imgOrder;


        [CrossView(nameof(OrderBarViewModel.OrderListBaseCell.ItemNameText))]
        public UILabel view3 => lblName;

        [CrossView(nameof(OrderBarViewModel.OrderListBaseCell.PriceText))]
        public UILabel view4 => lblPrice;

        [CrossView(nameof(OrderBarViewModel.OrderListBaseCell.QuantityText))]
        public UILabel view5 => lblCounter;
    }
}
