// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.Models.DAL;
using Core.ViewModels.Beer;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.CellView;
using UIKit;

namespace iOS.Storyboard
{
    public partial class OrderCell : ComponentTableViewCell<IOrderContent>
    {
        public OrderCell(IntPtr handle) : base(handle) { }

        protected override UIColor ColorSelector { get => UIColor.Clear; set => base.ColorSelector = value; }


        [CrossView(nameof(OrderViewModel.OrderListCell.CellContentRootView))]
        public UIView view11 => mainRoot;

        [CrossView(nameof(OrderViewModel.OrderListCell.ItemNameText))]
        public UILabel view1 => lblName;

        [CrossView(nameof(OrderViewModel.OrderListCell.QuantityText))]
        public UILabel view2 => lblCounter;

        [CrossView(nameof(OrderViewModel.OrderListCell.PriceText))]
        public UILabel view5 => lblPrice;

        [CrossView(nameof(OrderViewModel.OrderListCell.CategoryImage))]
        public UIImageView view3 => imgOrder;

        [CrossView(nameof(OrderViewModel.OrderListCell.RemoveOrderImage))]
        public UIImageView view4 => imgOrderRemove;


        [CrossView(nameof(OrderViewModel.OrderListCell.PlusText))]
        public UILabel view7 => lblPlus;

        [CrossView(nameof(OrderViewModel.OrderListCell.MinusText))]
        public UILabel view8 => lblMinus;
    }
}
