// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Storyboard
{
    public partial class FoodListCell : UITableViewCell
    {
        public FoodListCell(IntPtr handle) : base(handle) { }
    }
}
