// This file has been autogenerated from a class added in the UI designer.

using System;
using Int.iOS.Wrappers.Text;

namespace iOS.Storyboard
{
    public partial class WrapperHyperLabel : HyperLabel
    {
        public WrapperHyperLabel(IntPtr handle) : base(handle)
        {
        }
    }
}
