// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class Sign : BaseView<SignViewModel>
    {
        public Sign(IntPtr handle) : base(handle) { }
    }

    partial class Sign
    {
        [CrossView(nameof(SignViewModel.BackroundImage))]
        UIImageView view1 => imgBackround;

        [CrossView(nameof(SignViewModel.LogoImage))]
        UIImageView view2 => imgLogo;


        [CrossView(nameof(SignViewModel.PasswordWatchImage))]
        UIImageView view14 => imgHide;


        [CrossView(nameof(SignViewModel.EmailPlaceholderText))]
        UILabel view3 => lblEmailStatic;

        [CrossView(nameof(SignViewModel.EmailText))]
        UITextField view4 => txtEmail;

        [CrossView(nameof(SignViewModel.EmailLineText))]
        UIView view5 => viewEmail;


        [CrossView(nameof(SignViewModel.PasswordPlaceholderText))]
        UILabel view6 => lblPassword;

        [CrossView(nameof(SignViewModel.PasswordText))]
        UITextField view7 => txtPassword;

        [CrossView(nameof(SignViewModel.PasswordLineText))]
        UIView view8 => viewLinePassword;


        [CrossView(nameof(SignViewModel.PasswordForgotText))]
        UILabel view9 => lblForgotPassword;

        [CrossView(nameof(SignViewModel.SignInText))]
        UILabel view10 => lblSignIn;


        [CrossView(nameof(SignViewModel.ConnectFacebookText))]
        UILabel view11 => lblFacebook;

        [CrossView(nameof(SignViewModel.RegistrationDontAccountText))]
        UILabel view12 => lblDont;

        [CrossView(nameof(SignViewModel.SignUpText))]
        UILabel view13 => lblSignUp;
    }
}
