// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Core.ViewModels;
using Int.Core.Application.Menu.Contract;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class Home : BaseView<HomeViewModel>
    {
        public Home(IntPtr handle) : base(handle) { }

        protected override void BindViews()
        {
            base.BindViews();

            TableView.Source = ComponentViewSourceFactory.CreateForTable(nameof(HomeCell),
                                                                   new List<IItemMenu>(),
                                                                   TableView,
                                                                   crossCellModel: new HomeViewModel.HomeListCell(ModelView));
        }
    }

    partial class Home
    {
        [CrossView(nameof(HomeViewModel.LogoImage))]
        UIImageView view1 => imgLogo;

        [CrossView(nameof(HomeViewModel.ListView))]
        UITableView view2 => TableView;
    }
}
