// This file has been autogenerated from a class added in the UI designer.

using System;
using Int.iOS.Factories.Adapter.CellView;
using Core.Models.Contract;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Core.ViewModels;
using UIKit;

namespace iOS.Storyboard
{
    public partial class EventNameCell : ComponentTableViewCell<IEvent>
    {
        public EventNameCell(IntPtr handle) : base(handle) { }

        protected override UIColor ColorSelector { get => UIColor.Clear; set => base.ColorSelector = value; }

        [CrossView(nameof(EventsViewModel.EventNameListCell.CellContentRootView))]
        public UIView view1 => mainCell;

        [CrossView(nameof(EventsViewModel.EventNameListCell.NameText))]
        public UILabel view2 => lblEventName;

        [CrossView(nameof(EventsViewModel.EventNameListCell.EventTime))]
        public UILabel view4 => lblTime1;

        [CrossView(nameof(EventsViewModel.EventNameListCell.EventImage))]
        public UIImageView view3 => imgEvent;


        [CrossView(nameof(EventsViewModel.EventNameListCell.ContainerDateText))]
        public UILabel view5 => lblDate2;

        [CrossView(nameof(EventsViewModel.EventNameListCell.ContainerTimeText))]
        public UILabel view6 => lblTime2;
    }
}
