// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.Models.Contract;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.Abstraction;
using UIKit;

namespace iOS.Storyboard
{
    public partial class EventCollectionSubTagCell : CollectionViewCell<IEvent>
    {
        public EventCollectionSubTagCell(IntPtr handle) : base(handle) { }

        public override void OnBind(int position) { }

        [CrossView(nameof(EventsViewModel.EventsListSubTagCell.CellContentRootView))]
        public UIView view1 => mainView;

        [CrossView(nameof(EventsViewModel.EventsListSubTagCell.NameText))]
        public UILabel view2 => lblName;

        [CrossView(nameof(EventsViewModel.EventsListSubTagCell.EventHourTime))]
        public UILabel view6 => lblDate;


        [CrossView(nameof(EventsViewModel.EventsListSubTagCell.EventImage))]
        public UIImageView view3 => imgEvent;

        [CrossView(nameof(EventsViewModel.EventsListSubTagCell.ImageDateTimeBackground))]
        public UIImageView view4 => imgBackroundDate;

        [CrossView(nameof(EventsViewModel.EventsListSubTagCell.SeparatorDateTime))]
        public UIImageView view5 => imgSeparator;


        [CrossView(nameof(EventsViewModel.EventNameListCell.ContainerDateText))]
        public UILabel view7 => lblDate2;

        [CrossView(nameof(EventsViewModel.EventNameListCell.ContainerTimeText))]
        public UILabel view8 => lblTime2;
    }
}
