// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.Models.Contract;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.Abstraction;
using UIKit;

namespace iOS.Storyboard
{
    public partial class EventCollectionCell : CollectionViewCell<IEvent>
    {
        public EventCollectionCell(IntPtr handle) : base(handle) { }

        public override void OnBind(int position) { }

        [CrossView(nameof(EventsViewModel.EventsListTagCell.NameText))]
        public UILabel view2 => lblName;
    }
}
