// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels.Beer;
using Foundation;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.CellView;
using UIKit;

namespace iOS.Storyboard
{
    public partial class OrdersCell : ComponentTableViewCell<Core.Models.DTO.Order.Get.OrderModel>
    {
        public OrdersCell(IntPtr handle) : base(handle) { }

        protected override UIColor ColorSelector { get => UIColor.Clear; set => base.ColorSelector = value; }

        [CrossView(nameof(OrdersViewModel.OrdersListCell.CellContentRootView))]
        public UIView view11 => mainRoot;

        [CrossView(nameof(OrdersViewModel.OrdersListCell.ItemTypeOrder))]
        public UILabel view3 => lblTypeOrder;

        [CrossView(nameof(OrdersViewModel.OrdersListCell.PriceText))]
        public UILabel view4 => lblTotalPrice;

        [CrossView(nameof(OrdersViewModel.OrdersListCell.DateTimeText))]
        public UILabel view5 => lblDateTime;

        [CrossView(nameof(OrdersViewModel.OrdersListCell.OrderIdText))]
        public UILabel view51 => lblOrderId;
    }
}
