// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.ViewModels;
using Int.Core.Application.Menu.Contract;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.CellView;
using UIKit;

namespace iOS.Storyboard
{
    public partial class HomeCell : ComponentTableViewCell<IItemMenu>
    {
        public HomeCell(IntPtr handle) : base(handle) { }

        protected override UIColor ColorSelector { get => UIColor.Clear; set => base.ColorSelector = value; }


        [CrossView(nameof(HomeViewModel.HomeListCell.CellContentRootView))]
        public UIView view1 => viewRootCell;

        [CrossView(nameof(HomeViewModel.HomeListCell.NameText))]
        public UILabel view2 => lblName;

        [CrossView(nameof(HomeViewModel.HomeListCell.NameImage))]
        public UIImageView view3 => imgName;

    }
}
