// This file has been autogenerated from a class added in the UI designer.

using System;
using iOS.Page.BasePage;
using Core.ViewModels;

namespace iOS.Storyboard
{
    public partial class FoodList : BasePageNavigation<FoodViewModel>
    {
        public FoodList(IntPtr handle) : base(handle) { }
    }
}
