// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Core.ViewModels.Beer;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class Orders : BasePageNavigation<OrdersViewModel>
    {
        public Orders(IntPtr handle) : base(handle)
        {
        }

        protected override void BindViews()
        {
            base.BindViews();

            var source = ComponentViewSourceFactory.CreateForTable(nameof(OrdersCell),
                                                                   new List<Core.Models.DTO.Order.Get.OrderModel>(),
                                                                   TableView,
                                                                   crossCellModel: new OrdersViewModel.OrdersListCell(ModelView));
            TableView.Source = source;
        }
    }

    partial class Orders
    {
        [CrossView(nameof(OrdersViewModel.ListView))]
        UITableView view4 => TableView;

        [CrossView(nameof(OrdersViewModel.BackroundContent))]
        UIView view5 => viewBackroundContent;
    }
}
