// This file has been autogenerated from a class added in the UI designer.

using System;
using Int.iOS.Factories.Adapter.CellView;
using Core.Models.Contract;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using UIKit;
using Core.ViewModels;

namespace iOS.Storyboard
{
    public partial class FeedbackCell : ComponentTableViewCell<IFeedback>
    {
        public FeedbackCell(IntPtr handle) : base(handle) { }

        protected override UIColor ColorSelector { get => UIColor.Clear; set => base.ColorSelector = value; }

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.CellContentRootView))]
        public UIView view1 => mainCell;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.ServiceText))]
        public UILabel view2 => lblCategory;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.Service2Text))]
        public UILabel view22 => lblServiceName;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.ServiceImage))]
        public UIImageView view3 => imgCategory;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.ImageStatus))]
        public UIImageView view4 => imgStatus;


        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.FeedbackVotes))]
        public UILabel view5 => lblStatus2;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.FeedbackStatus))]
        public UILabel view6 => lblStatus1;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.ProgressView))]
        public UIView view7 => viewProcent;


        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.ProgressView20))]
        public UIView view8 => viewProcent20;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.ProgressView40))]
        public UIView view9 => viewProcent40;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.ProgressView60))]
        public UIView view10 => viewProcent60;

        [CrossView(nameof(FeedbackViewModel.FeedbackListCell.ProgressView80))]
        public UIView view11 => viewProcent80;
    }
}
