// This file has been autogenerated from a class added in the UI designer.

using System;
using Core.Models.Contract;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter.Abstraction;
using UIKit;

namespace iOS.Storyboard
{
    public partial class StatusCollectionCell : CollectionViewCell<IFeedback>
    {
        public StatusCollectionCell(IntPtr handle) : base(handle) { }

        [CrossView(nameof(FeedbackGiveViewModel.StatusFeedbackListCell.CellContentRootView))]
        UIView view3 => mainView;

        [CrossView(nameof(FeedbackGiveViewModel.StatusFeedbackListCell.ServiceImage))]
        UIImageView view1 => imgStatus;

        [CrossView(nameof(FeedbackGiveViewModel.StatusFeedbackListCell.ServiceText))]
        UILabel view2 => lblStatus;

        public override void OnBind(int position) { }
    }
}
