// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Core.Helpers.Manager.Feedback;
using Core.Models.Contract;
using Core.ViewModels;
using Int.Core.Wrappers.Widget.CrossViewInjection;
using Int.iOS.Factories.Adapter;
using iOS.Page.BasePage;
using UIKit;

namespace iOS.Storyboard
{
    public partial class FeedbackGive : BasePageNavigation<FeedbackGiveViewModel>
    {
        private readonly int _heightAndSpaceStatus = 69;

        public FeedbackGive(IntPtr handle) : base(handle) { }

        protected override void BindViews()
        {
            base.BindViews();

            CollectionView.Source = ComponentViewSourceFactory.CreateForCollection(nameof(StatusCollectionCell),
                                                                                   new List<IFeedback>(),
                                                                                   CollectionView,
                                                                                   crossCellModel: new FeedbackGiveViewModel.StatusFeedbackListCell(ModelView),
                                                                                   widthCountCell: Tuple.Create(_heightAndSpaceStatus, FeedbackManager.Instance.GetItem().Count));
        }
    }

    partial class FeedbackGive
    {
        [CrossView(nameof(FeedbackGiveViewModel.ListView))]
        public UICollectionView view1 => CollectionView;

        [CrossView(nameof(FeedbackGiveViewModel.BackgroundContent))]
        public UIView view2 => viewContent;

        [CrossView(nameof(FeedbackGiveViewModel.ConfirmButton))]
        public UILabel view3 => lblConfirm;

        [CrossView(nameof(FeedbackGiveViewModel.TitleText))]
        public UILabel view4 => lblTitle;



        [CrossView(nameof(FeedbackGiveViewModel.SericeText))]
        public UILabel view5 => lblService;

        [CrossView(nameof(FeedbackGiveViewModel.HeaderBackroundRoundText))]
        public UIView view6 => viewBackroundService;

        [CrossView(nameof(FeedbackGiveViewModel.BackroundServiceImage))]
        public UIImageView view7 => imgService;
    }
}
